### ISSUE TITLE
Default blueprint uses outdated testdouble dependency

### ISSUE THREAD

**Issue by makepanic** [isleofcode/ember-cli-testdouble#13]
Hi, thanks for this addon.

Your default blueprint adds [testdouble@2.x](https://github.com/isleofcode/ember-cli-testdouble/blob/master/blueprints/ember-cli-testdouble/index.js#L13) but they're already [at @3.x](https://github.com/testdouble/testdouble.js/blob/master/CHANGELOG.md#v381-2018-05-05).

Would you be interested in updating the blueprint?
I can create a PR which bumps testdouble.

**Comment by alexblom** [comment]
Absolutely - thanks for the PR. I'll give it a test tomorrow.
